services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_auth_api
    environment:
      - 'MYSQL_DATABASE=auth_db'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: